# Generated by Django 4.0.4 on 2022-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionName', models.CharField(max_length=30)),
                ('TransactionValue', models.IntegerField()),
                ('TransactionDate', models.DateField()),
            ],
        ),
    ]
